SHIP_CONTROL_VERSION = 94b3f098347d0c7326cbcb12cf26672f0f15daf0
SHIP_CONTROL_SITE = https://github.com/MooseTheBrown/ship-control
SHIP_CONTROL_SITE_METHOD = git
SHIP_CONTROL_INSTALL_STAGING = YES
#SHIP_CONTROL_INSTALL_TARGET = NO
#SHIP_CONTROL_CONF_OPTS = -DBUILD_TESTS=ON
#SHIP_CONTROL_DEPENDENCIES =

$(eval $(cmake-package))
